# Ansible configuration file to deploy Oauth2.0 Flask microservice

- name: Deploy {{host}}
  hosts: "{{host}}"
  remote_user: ubuntu
  vars:
    image: gettalent/resume-parsing-service
  sudo: no
  tasks:
#    # Get latest code from git
#    - name: Get stuff from git
#      git:
#        repo: git@github.com:gettalent/talent-flask-services.git
#        dest: /home/ubuntu/talent-flask-services/
#        version: "{{branch}}"
#        accept_hostkey: yes

    # Stop and remove flask microservice docker container
    - name: Stop Flask service and remove docker container
      docker:
        image: "{{image}}"
        state: absent

    # Remove Docker Images from local repository
    - name: Remove docker images from local repository
      docker_image:
        name: "{{image}}"
        state: absent

    # Build a new version of docker image
    - name: check or build image
      docker_image:
        path: "/home/ubuntu/talent-flask-services/resume_service/"
        name: "{{image}}"
        state: build

    # Start a Flask microservice docker container
    - name: Start Flask service Docker container
      docker:
        image: "{{image}}"
        state: reloaded
        ports:
          - "80:80"
          - "443:443"
        env:
            GT_ENVIRONMENT: "{{GT_ENVIRONMENT}}"
        volumes:
          - "/usr/local/etc/ssl:/etc/nginx/ssl"
#          - "/home/ubuntu/talent-flask-services:/root/talent-flask-services"