# Ansible configuration file to deploy Oauth2.0 Flask microservice

- name: Deploy {{host}}
  hosts: "{{host}}"
  remote_user: ubuntu
  vars:
    image: gettalent/authservice
  sudo: no
  tasks:
    # Get latest code from git
    - name: Get stuff from git
      git:
        repo: git@github.com:Veechi/AuthService.git
        dest: /home/ubuntu/AuthService/
        version: "{{branch}}"
        accept_hostkey: yes

    # Stop and remove a oauth2.0 flask microservice docker container
    - name: Oauth2.0 flask service stop and remove docker container
      docker:
        image: "{{image}}"
        state: absent

    # Remove Docker Images from local repository
    - name: Remove docker images from local repository
      docker_image:
        name: "{{image}}"
        state: absent

    # Build a new version of docker image
    - name: check or build image
      docker_image:
        path: "/home/ubuntu/AuthService/"
        name: "{{image}}"
        state: build

    # Start a oauth2.0 flask microservice docker container
    - name: Oauth2.0 flask service start docker container
      docker:
        image: "{{image}}"
        state: reloaded
        ports:
          - "80:80"
          - "443:443"
        env:
            GT_ENVIRONMENT: "{{GT_ENVIRONMENT}}"
        volumes:
          - "/usr/local/etc/ssl:/etc/nginx/ssl"