"""
Helper functions to get started after a local database reset.

Steps:
    1) Recreate talent_local in your local MySQL using the talent_web user (DROP/CREATE syntax).
    2) Run auth service to create all tables.
    3) Run this script `python scripts/create_db_defaults.py` to populate the static values stored
       in prod/staging.
"""
import datetime

from sqlalchemy import Column, create_engine, INT, TEXT, VARCHAR, BOOLEAN, TIMESTAMP, DATETIME
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker


engine = create_engine('mysql://talent_web:s!loc976892@127.0.0.1/talent_local')
Session = sessionmaker(bind=engine)
session = Session()
Base = declarative_base()


ROLES = ('ADMIN', 'DOMAIN_ADMIN', 'TALENT_ADMIN', 'USER')

PERMISSIONS = (
    'CAN_ADD_CAMPAIGNS', 'CAN_ADD_CANDIDATES', 'CAN_ADD_CANDIDATE_CONTACT_HISTORY',
    'CAN_ADD_CANDIDATE_NOTES', 'CAN_ADD_CANDIDATE_PRIMARY_INFO',
    'CAN_ADD_CANDIDATE_SOCIAL_PROFILE', 'CAN_ADD_DOMAINS', 'CAN_ADD_DOMAIN_GROUPS',
    'CAN_ADD_SMART_LISTS', 'CAN_ADD_TALENT_PIPELINES', 'CAN_ADD_TALENT_POOLS',
    'CAN_ADD_USERS', 'CAN_ADD_WIDGETS', 'CAN_DELETE_CAMPAIGNS', 'CAN_DELETE_CANDIDATES',
    'CAN_DELETE_CANDIDATE_CONTACT_HISTORY', 'CAN_DELETE_CANDIDATE_NOTES',
    'CAN_DELETE_CANDIDATE_PRIMARY_INFO', 'CAN_DELETE_CANDIDATE_SOCIAL_PROFILE',
    'CAN_DELETE_DOMAINS', 'CAN_DELETE_DOMAIN_GROUPS', 'CAN_DELETE_SMART_LISTS',
    'CAN_DELETE_TALENT_PIPELINES', 'CAN_DELETE_TALENT_POOLS', 'CAN_DELETE_USERS',
    'CAN_DELETE_WIDGETS', 'CAN_EDIT_CAMPAIGNS', 'CAN_EDIT_CANDIDATES',
    'CAN_EDIT_CANDIDATE_CONTACT_HISTORY', 'CAN_EDIT_CANDIDATE_NOTES',
    'CAN_EDIT_CANDIDATE_PRIMARY_INFO', 'CAN_EDIT_CANDIDATE_SOCIAL_PROFILE',
    'CAN_EDIT_DOMAINS', 'CAN_EDIT_DOMAIN_GROUPS', 'CAN_EDIT_SMART_LISTS',
    'CAN_EDIT_TALENT_PIPELINES', 'CAN_EDIT_TALENT_POOLS', 'CAN_EDIT_USERS',
    'CAN_EDIT_USER_ROLE', 'CAN_EDIT_WIDGETS', 'CAN_GET_CAMPAIGNS',
    'CAN_GET_CANDIDATES', 'CAN_GET_CANDIDATE_CONTACT_HISTORY', 'CAN_GET_CANDIDATE_NOTES',
    'CAN_GET_CANDIDATE_PRIMARY_INFO', 'CAN_GET_CANDIDATE_SOCIAL_PROFILE',
    'CAN_GET_DOMAINS', 'CAN_GET_DOMAIN_GROUPS', 'CAN_GET_SMART_LISTS',
    'CAN_GET_TALENT_PIPELINES', 'CAN_GET_TALENT_POOLS', 'CAN_GET_USERS',
    'CAN_GET_USER_ROLE', 'CAN_GET_WIDGETS', 'CAN_IMPERSONATE_USERS'
)

PERMISSION_ROLE_PAIRS = (
    ('CAN_EDIT_USER_ROLE', 'ADMIN'),
    ('CAN_ADD_TALENT_PIPELINES', 'ADMIN'),
    ('CAN_ADD_CAMPAIGNS', 'ADMIN'),
    ('CAN_EDIT_CANDIDATE_NOTES', 'ADMIN'),
    ('CAN_EDIT_WIDGETS', 'ADMIN'),
    ('CAN_GET_DOMAIN_GROUPS', 'ADMIN'),
    ('CAN_ADD_CANDIDATES', 'ADMIN'),
    ('CAN_ADD_USERS', 'ADMIN'),
    ('CAN_DELETE_SMART_LISTS', 'ADMIN'),
    ('CAN_EDIT_CANDIDATE_PRIMARY_INFO', 'ADMIN'),
    ('CAN_GET_CAMPAIGNS', 'ADMIN'),
    ('CAN_GET_SMART_LISTS', 'ADMIN'),
    ('CAN_ADD_WIDGETS', 'ADMIN'),
    ('CAN_ADD_CANDIDATE_CONTACT_HISTORY', 'ADMIN'),
    ('CAN_DELETE_TALENT_PIPELINES', 'ADMIN'),
    ('CAN_EDIT_CANDIDATE_SOCIAL_PROFILE', 'ADMIN'),
    ('CAN_GET_CANDIDATES', 'ADMIN'),
    ('CAN_GET_TALENT_PIPELINES', 'ADMIN'),
    ('CAN_DELETE_CAMPAIGNS', 'ADMIN'),
    ('CAN_ADD_CANDIDATE_NOTES', 'ADMIN'),
    ('CAN_GET_CANDIDATE_CONTACT_HISTORY', 'ADMIN'),
    ('CAN_DELETE_CANDIDATES', 'ADMIN'),
    ('CAN_GET_TALENT_POOLS', 'ADMIN'),
    ('CAN_DELETE_USERS', 'ADMIN'),
    ('CAN_ADD_CANDIDATE_PRIMARY_INFO', 'ADMIN'),
    ('CAN_DELETE_WIDGETS', 'ADMIN'),
    ('CAN_EDIT_SMART_LISTS', 'ADMIN'),
    ('CAN_GET_CANDIDATE_NOTES', 'ADMIN'),
    ('CAN_DELETE_CANDIDATE_CONTACT_HISTORY', 'ADMIN'),
    ('CAN_GET_USERS', 'ADMIN'),
    ('CAN_ADD_CANDIDATE_SOCIAL_PROFILE', 'ADMIN'),
    ('CAN_GET_USER_ROLE', 'ADMIN'),
    ('CAN_EDIT_CAMPAIGNS', 'ADMIN'),
    ('CAN_EDIT_TALENT_PIPELINES', 'ADMIN'),
    ('CAN_GET_CANDIDATE_PRIMARY_INFO', 'ADMIN'),
    ('CAN_DELETE_CANDIDATE_NOTES', 'ADMIN'),
    ('CAN_EDIT_TALENT_POOLS', 'ADMIN'),
    ('CAN_GET_WIDGETS', 'ADMIN'),
    ('CAN_EDIT_CANDIDATES', 'ADMIN'),
    ('CAN_GET_CANDIDATE_SOCIAL_PROFILE', 'ADMIN'),
    ('CAN_DELETE_CANDIDATE_PRIMARY_INFO', 'ADMIN'),
    ('CAN_ADD_SMART_LISTS', 'ADMIN'),
    ('CAN_EDIT_USERS', 'ADMIN'),
    ('CAN_EDIT_CANDIDATE_CONTACT_HISTORY', 'ADMIN'),
    ('CAN_GET_DOMAINS', 'ADMIN'),
    ('CAN_DELETE_CANDIDATE_SOCIAL_PROFILE', 'ADMIN'),
    ('CAN_GET_DOMAINS', 'DOMAIN_ADMIN'),
    ('CAN_DELETE_CANDIDATE_SOCIAL_PROFILE', 'DOMAIN_ADMIN'),
    ('CAN_EDIT_USER_ROLE', 'DOMAIN_ADMIN'),
    ('CAN_ADD_TALENT_PIPELINES', 'DOMAIN_ADMIN'),
    ('CAN_ADD_CAMPAIGNS', 'DOMAIN_ADMIN'),
    ('CAN_ADD_TALENT_POOLS', 'DOMAIN_ADMIN'),
    ('CAN_DELETE_DOMAIN_GROUPS', 'DOMAIN_ADMIN'),
    ('CAN_EDIT_CANDIDATE_NOTES', 'DOMAIN_ADMIN'),
    ('CAN_EDIT_WIDGETS', 'DOMAIN_ADMIN'),
    ('CAN_GET_DOMAIN_GROUPS', 'DOMAIN_ADMIN'),
    ('CAN_ADD_CANDIDATES', 'DOMAIN_ADMIN'),
    ('CAN_ADD_USERS', 'DOMAIN_ADMIN'),
    ('CAN_DELETE_SMART_LISTS', 'DOMAIN_ADMIN'),
    ('CAN_EDIT_CANDIDATE_PRIMARY_INFO', 'DOMAIN_ADMIN'),
    ('CAN_GET_CAMPAIGNS', 'DOMAIN_ADMIN'),
    ('CAN_GET_SMART_LISTS', 'DOMAIN_ADMIN'),
    ('CAN_ADD_WIDGETS', 'DOMAIN_ADMIN'),
    ('CAN_ADD_CANDIDATE_CONTACT_HISTORY', 'DOMAIN_ADMIN'),
    ('CAN_DELETE_TALENT_PIPELINES', 'DOMAIN_ADMIN'),
    ('CAN_EDIT_CANDIDATE_SOCIAL_PROFILE', 'DOMAIN_ADMIN'),
    ('CAN_GET_CANDIDATES', 'DOMAIN_ADMIN'),
    ('CAN_GET_TALENT_PIPELINES', 'DOMAIN_ADMIN'),
    ('CAN_DELETE_CAMPAIGNS', 'DOMAIN_ADMIN'),
    ('CAN_DELETE_TALENT_POOLS', 'DOMAIN_ADMIN'),
    ('CAN_EDIT_DOMAINS', 'DOMAIN_ADMIN'),
    ('CAN_ADD_CANDIDATE_NOTES', 'DOMAIN_ADMIN'),
    ('CAN_EDIT_DOMAIN_GROUPS', 'DOMAIN_ADMIN'),
    ('CAN_GET_CANDIDATE_CONTACT_HISTORY', 'DOMAIN_ADMIN'),
    ('CAN_DELETE_CANDIDATES', 'DOMAIN_ADMIN'),
    ('CAN_GET_TALENT_POOLS', 'DOMAIN_ADMIN'),
    ('CAN_DELETE_USERS', 'DOMAIN_ADMIN'),
    ('CAN_ADD_CANDIDATE_PRIMARY_INFO', 'DOMAIN_ADMIN'),
    ('CAN_DELETE_WIDGETS', 'DOMAIN_ADMIN'),
    ('CAN_EDIT_SMART_LISTS', 'DOMAIN_ADMIN'),
    ('CAN_GET_CANDIDATE_NOTES', 'DOMAIN_ADMIN'),
    ('CAN_DELETE_CANDIDATE_CONTACT_HISTORY', 'DOMAIN_ADMIN'),
    ('CAN_GET_USERS', 'DOMAIN_ADMIN'),
    ('CAN_ADD_CANDIDATE_SOCIAL_PROFILE', 'DOMAIN_ADMIN'),
    ('CAN_EDIT_TALENT_PIPELINES', 'DOMAIN_ADMIN'),
    ('CAN_GET_USER_ROLE', 'DOMAIN_ADMIN'),
    ('CAN_EDIT_CAMPAIGNS', 'DOMAIN_ADMIN'),
    ('CAN_GET_CANDIDATE_PRIMARY_INFO', 'DOMAIN_ADMIN'),
    ('CAN_DELETE_CANDIDATE_NOTES', 'DOMAIN_ADMIN'),
    ('CAN_ADD_DOMAIN_GROUPS', 'DOMAIN_ADMIN'),
    ('CAN_EDIT_TALENT_POOLS', 'DOMAIN_ADMIN'),
    ('CAN_GET_WIDGETS', 'DOMAIN_ADMIN'),
    ('CAN_EDIT_CANDIDATES', 'DOMAIN_ADMIN'),
    ('CAN_GET_CANDIDATE_SOCIAL_PROFILE', 'DOMAIN_ADMIN'),
    ('CAN_DELETE_CANDIDATE_PRIMARY_INFO', 'DOMAIN_ADMIN'),
    ('CAN_ADD_SMART_LISTS', 'DOMAIN_ADMIN'),
    ('CAN_EDIT_USERS', 'DOMAIN_ADMIN'),
    ('CAN_EDIT_CANDIDATE_CONTACT_HISTORY', 'DOMAIN_ADMIN'),
    ('CAN_EDIT_CANDIDATE_CONTACT_HISTORY', 'TALENT_ADMIN'),
    ('CAN_GET_DOMAINS', 'TALENT_ADMIN'),
    ('CAN_DELETE_CANDIDATE_SOCIAL_PROFILE', 'TALENT_ADMIN'),
    ('CAN_EDIT_USER_ROLE', 'TALENT_ADMIN'),
    ('CAN_ADD_TALENT_PIPELINES', 'TALENT_ADMIN'),
    ('CAN_DELETE_DOMAINS', 'TALENT_ADMIN'),
    ('CAN_ADD_CAMPAIGNS', 'TALENT_ADMIN'),
    ('CAN_ADD_TALENT_POOLS', 'TALENT_ADMIN'),
    ('CAN_DELETE_DOMAIN_GROUPS', 'TALENT_ADMIN'),
    ('CAN_EDIT_CANDIDATE_NOTES', 'TALENT_ADMIN'),
    ('CAN_EDIT_WIDGETS', 'TALENT_ADMIN'),
    ('CAN_GET_DOMAIN_GROUPS', 'TALENT_ADMIN'),
    ('CAN_ADD_CANDIDATES', 'TALENT_ADMIN'),
    ('CAN_ADD_USERS', 'TALENT_ADMIN'),
    ('CAN_DELETE_SMART_LISTS', 'TALENT_ADMIN'),
    ('CAN_EDIT_CANDIDATE_PRIMARY_INFO', 'TALENT_ADMIN'),
    ('CAN_GET_CAMPAIGNS', 'TALENT_ADMIN'),
    ('CAN_GET_SMART_LISTS', 'TALENT_ADMIN'),
    ('CAN_ADD_WIDGETS', 'TALENT_ADMIN'),
    ('CAN_ADD_CANDIDATE_CONTACT_HISTORY', 'TALENT_ADMIN'),
    ('CAN_DELETE_TALENT_PIPELINES', 'TALENT_ADMIN'),
    ('CAN_EDIT_CANDIDATE_SOCIAL_PROFILE', 'TALENT_ADMIN'),
    ('CAN_GET_CANDIDATES', 'TALENT_ADMIN'),
    ('CAN_GET_TALENT_PIPELINES', 'TALENT_ADMIN'),
    ('CAN_DELETE_CAMPAIGNS', 'TALENT_ADMIN'),
    ('CAN_DELETE_TALENT_POOLS', 'TALENT_ADMIN'),
    ('CAN_EDIT_DOMAINS', 'TALENT_ADMIN'),
    ('CAN_ADD_CANDIDATE_NOTES', 'TALENT_ADMIN'),
    ('CAN_EDIT_DOMAIN_GROUPS', 'TALENT_ADMIN'),
    ('CAN_GET_CANDIDATE_CONTACT_HISTORY', 'TALENT_ADMIN'),
    ('CAN_DELETE_CANDIDATES', 'TALENT_ADMIN'),
    ('CAN_GET_TALENT_POOLS', 'TALENT_ADMIN'),
    ('CAN_DELETE_USERS', 'TALENT_ADMIN'),
    ('CAN_ADD_CANDIDATE_PRIMARY_INFO', 'TALENT_ADMIN'),
    ('CAN_DELETE_WIDGETS', 'TALENT_ADMIN'),
    ('CAN_EDIT_SMART_LISTS', 'TALENT_ADMIN'),
    ('CAN_GET_CANDIDATE_NOTES', 'TALENT_ADMIN'),
    ('CAN_DELETE_CANDIDATE_CONTACT_HISTORY', 'TALENT_ADMIN'),
    ('CAN_GET_USERS', 'TALENT_ADMIN'),
    ('CAN_ADD_CANDIDATE_SOCIAL_PROFILE', 'TALENT_ADMIN'),
    ('CAN_EDIT_TALENT_PIPELINES', 'TALENT_ADMIN'),
    ('CAN_ADD_DOMAINS', 'TALENT_ADMIN'),
    ('CAN_GET_USER_ROLE', 'TALENT_ADMIN'),
    ('CAN_EDIT_CAMPAIGNS', 'TALENT_ADMIN'),
    ('CAN_GET_CANDIDATE_PRIMARY_INFO', 'TALENT_ADMIN'),
    ('CAN_DELETE_CANDIDATE_NOTES', 'TALENT_ADMIN'),
    ('CAN_ADD_DOMAIN_GROUPS', 'TALENT_ADMIN'),
    ('CAN_EDIT_TALENT_POOLS', 'TALENT_ADMIN'),
    ('CAN_GET_WIDGETS', 'TALENT_ADMIN'),
    ('CAN_EDIT_CANDIDATES', 'TALENT_ADMIN'),
    ('CAN_GET_CANDIDATE_SOCIAL_PROFILE', 'TALENT_ADMIN'),
    ('CAN_DELETE_CANDIDATE_PRIMARY_INFO', 'TALENT_ADMIN'),
    ('CAN_IMPERSONATE_USERS', 'TALENT_ADMIN'),
    ('CAN_ADD_SMART_LISTS', 'TALENT_ADMIN'),
    ('CAN_EDIT_USERS', 'TALENT_ADMIN'),
    ('CAN_ADD_CAMPAIGNS', 'USER'),
    ('CAN_EDIT_CANDIDATE_NOTES', 'USER'),
    ('CAN_GET_DOMAIN_GROUPS', 'USER'),
    ('CAN_ADD_CANDIDATES', 'USER'),
    ('CAN_DELETE_SMART_LISTS', 'USER'),
    ('CAN_EDIT_CANDIDATE_PRIMARY_INFO', 'USER'),
    ('CAN_GET_CAMPAIGNS', 'USER'),
    ('CAN_GET_SMART_LISTS', 'USER'),
    ('CAN_ADD_CANDIDATE_CONTACT_HISTORY', 'USER'),
    ('CAN_DELETE_TALENT_PIPELINES', 'USER'),
    ('CAN_EDIT_CANDIDATE_SOCIAL_PROFILE', 'USER'),
    ('CAN_GET_CANDIDATES', 'USER'),
    ('CAN_GET_TALENT_PIPELINES', 'USER'),
    ('CAN_DELETE_CAMPAIGNS', 'USER'),
    ('CAN_ADD_CANDIDATE_NOTES', 'USER'),
    ('CAN_GET_CANDIDATE_CONTACT_HISTORY', 'USER'),
    ('CAN_GET_TALENT_POOLS', 'USER'),
    ('CAN_ADD_CANDIDATE_PRIMARY_INFO', 'USER'),
    ('CAN_EDIT_SMART_LISTS', 'USER'),
    ('CAN_GET_CANDIDATE_NOTES', 'USER'),
    ('CAN_DELETE_CANDIDATE_CONTACT_HISTORY', 'USER'),
    ('CAN_GET_USERS', 'USER'),
    ('CAN_ADD_CANDIDATE_SOCIAL_PROFILE', 'USER'),
    ('CAN_EDIT_CAMPAIGNS', 'USER'),
    ('CAN_EDIT_TALENT_PIPELINES', 'USER'),
    ('CAN_GET_CANDIDATE_PRIMARY_INFO', 'USER'),
    ('CAN_DELETE_CANDIDATE_NOTES', 'USER'),
    ('CAN_GET_WIDGETS', 'USER'),
    ('CAN_EDIT_CANDIDATES', 'USER'),
    ('CAN_GET_CANDIDATE_SOCIAL_PROFILE', 'USER'),
    ('CAN_DELETE_CANDIDATE_PRIMARY_INFO', 'USER'),
    ('CAN_ADD_SMART_LISTS', 'USER'),
    ('CAN_EDIT_USERS', 'USER'),
    ('CAN_EDIT_CANDIDATE_CONTACT_HISTORY', 'USER'),
    ('CAN_GET_DOMAINS', 'USER'),
    ('CAN_DELETE_CANDIDATE_SOCIAL_PROFILE', 'USER'),
    ('CAN_ADD_TALENT_PIPELINES', 'USER')
)

CANDIDATE_STATUSES = (
     ('New', 'Newly added candidate'),
     ('Contacted', 'Candidate is contacted'),
     ('Unqualified', 'Candidate is unqualified'),
     ('Qualified', 'Candidate is qualified'),
     ('Prospect', 'Candidate', 'is a prospect'),
     ('Candidate', 'Candidate', 'is highly prospective'),
     ('Hired', 'Candidate is hired'),
     ('Connector', None)
)



class Role(Base):
    __tablename__ = 'role'
    id = Column(INT, primary_key=True)
    name = Column(VARCHAR(255), nullable=False, unique=True)


class Permission(Base):
    __tablename__ = 'permission'
    id = Column(INT, primary_key=True)
    name = Column(VARCHAR(255), nullable=False, unique=True)


class PermissionsOfRoles(Base):
    __tablename__ = 'permissions_of_role'
    id = Column(INT, primary_key=True)
    role_id = Column('RoleId', VARCHAR(255), nullable=False, unique=True)
    permission_id = Column('PermissionId', VARCHAR(255), nullable=False, unique=True)


class CandidateStatus(Base):
    __tablename__ = 'candidate_status'
    id = Column('Id', INT, primary_key=True)
    description = Column('Description', VARCHAR(100))
    notes = Column('Notes', VARCHAR(500))
    updated_time = Column('UpdatedTime', TIMESTAMP, default=datetime.datetime.utcnow)


def create_roles():
    for role in ROLES:
        session.add(Role(name=role))
        session.commit()

def create_permissions():
    for permission in PERMISSIONS:
        session.add(Permission(name=permission))
        session.commit()

def create_permissions_of_roles():
    for pair in PERMISSION_ROLE_PAIRS:
        permission = session.query(Permission).filter_by(name=pair[0]).first()
        role = session.query(Role).filter_by(name=pair[1]).first()
        session.add(PermissionsOfRoles(role_id=role.id, permission_id=permission.id))
        session.commit()

def create_candidate_status():
    for status_pair in CANDIDATE_STATUSES:
        session.add(CandidateStatus(description=status_pair[0], notes=status_pair[1]))
        session.commit()

# TODO: email labels
if __name__ == "__main__":
    create_roles()
    create_permissions()
    create_permissions_of_roles()
    create_candidate_status()
