"""
This file contains Base APP URls of all services
"""
from ..common_config import GT_ENVIRONMENT

LOCAL_HOST = 'http://127.0.0.1'
TALENT_DOMAIN = '.gettalent.com'
QA_EXTENSION = '-webdev'
AUTH_SERVICE = 'auth-service'
ACTIVITY_SERVICE = 'activity-service'
RESUME_SERVICE = 'resume-service'
USER_SERVICE = 'user-service'
CANDIDATE_SERVICE = 'candidate-service'
WIDGET_SERVICE = 'widget-service'
SOCIAL_NETWORK_SERVICE = 'social-network-service'
SMS_CAMPAIGN_SERVICE = 'sms-campaign-service'
SCHEDULER_SERVICE = 'scheduler-service'

if GT_ENVIRONMENT in ['dev', 'circle']:
    # GTDevBaseUrls
    AUTH_SERVICE_APP_URL = LOCAL_HOST + ':8001'
    ACTIVITY_SERVICE_APP_URL = LOCAL_HOST + ':8002'
    RESUME_SERVICE_APP_URL = LOCAL_HOST + ':8003'
    USER_SERVICE_APP_URL = LOCAL_HOST + ':8004'
    CANDIDATE_SERVICE_APP_URL = LOCAL_HOST + ':8005'
    WIDGET_SERVICE_APP_URL = LOCAL_HOST + ':8006'
    SOCIAL_NETWORK_SERVICE_APP_URL = LOCAL_HOST + ':8007'
    SMS_CAMPAIGN_SERVICE_APP_URL = LOCAL_HOST + ':8008'
    SCHEDULER_SERVICE_APP_URL = LOCAL_HOST + ':8009'
elif GT_ENVIRONMENT == 'qa':
    # TODO: need to verify once app is up
    AUTH_SERVICE_APP_URL = AUTH_SERVICE + QA_EXTENSION + TALENT_DOMAIN
    ACTIVITY_SERVICE_APP_URL = ACTIVITY_SERVICE + QA_EXTENSION + TALENT_DOMAIN
    RESUME_SERVICE_APP_URL = RESUME_SERVICE + QA_EXTENSION + TALENT_DOMAIN
    USER_SERVICE_APP_URL = USER_SERVICE + QA_EXTENSION + TALENT_DOMAIN
    CANDIDATE_SERVICE_APP_URL = CANDIDATE_SERVICE + QA_EXTENSION + TALENT_DOMAIN
    WIDGET_SERVICE_APP_URL = WIDGET_SERVICE + QA_EXTENSION + TALENT_DOMAIN
    SOCIAL_NETWORK_SERVICE_APP_URL = SOCIAL_NETWORK_SERVICE + QA_EXTENSION + TALENT_DOMAIN
    SMS_CAMPAIGN_SERVICE_APP_URL = SMS_CAMPAIGN_SERVICE + QA_EXTENSION + TALENT_DOMAIN
    SCHEDULER_SERVICE_APP_URL = SCHEDULER_SERVICE + QA_EXTENSION + TALENT_DOMAIN
elif GT_ENVIRONMENT == 'prod':
    # TODO: need to verify once app is up
    AUTH_SERVICE_APP_URL = AUTH_SERVICE + TALENT_DOMAIN
    ACTIVITY_SERVICE_APP_URL = ACTIVITY_SERVICE + TALENT_DOMAIN
    RESUME_SERVICE_APP_URL = RESUME_SERVICE + TALENT_DOMAIN
    USER_SERVICE_APP_URL = USER_SERVICE + TALENT_DOMAIN
    CANDIDATE_SERVICE_APP_URL = CANDIDATE_SERVICE + TALENT_DOMAIN
    WIDGET_SERVICE_APP_URL = WIDGET_SERVICE + TALENT_DOMAIN
    SOCIAL_NETWORK_SERVICE_APP_URL = SOCIAL_NETWORK_SERVICE + TALENT_DOMAIN
    SMS_CAMPAIGN_SERVICE_APP_URL = SMS_CAMPAIGN_SERVICE + TALENT_DOMAIN
    SCHEDULER_SERVICE_APP_URL = SCHEDULER_SERVICE + TALENT_DOMAIN
else:
    raise Exception("Environment variable GT_ENVIRONMENT not set correctly - could not run app.")
